#!/usr/bin/env python3
"""Generate CIUNIT-HANDOFF.md: which posts are candidates to move to CIunit.

Reads the human judgment in tools/post-classification.tsv and joins it with
facts pulled from the posts themselves (dates, live URLs, word counts, image
counts, and the publisher/DOI links each post cites), so the resulting document
can be handed to whoever -- or whatever -- is working on ciunit.github.io.
"""
import json
import pathlib
import re
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
POSTS = ROOT / "_posts"
OUT = ROOT / "CIUNIT-HANDOFF.md"
SITE = "https://kencaldeira.com"

CATEGORIES = [
    ("paper", "Writes up a specific paper",
     "These posts explain or announce a particular peer-reviewed paper, "
     "usually Ken's own. They map directly onto CIunit publication pages and "
     "are the strongest candidates to move."),
    ("science", "Substantive science, not tied to one paper",
     "Explainers, analyses, technical critiques and lectures. Real scientific "
     "content, but without a single paper to attach it to -- these would need "
     "a home on CIunit such as a notes or commentary section."),
    ("practice", "How research works",
     "Publishing, peer review, reproducibility, choosing problems, "
     "science communication, policy comment. Could plausibly live on either "
     "site; worth deciding as a group rather than one by one."),
    ("personal", "Stays on the blog",
     "Personal, cultural, political or humorous writing. Listed for "
     "completeness so nothing is unaccounted for."),
]

# Publisher domains worth surfacing as "this post cites a paper".
PUBLISHER = re.compile(
    r"https?://[^\s\)\(\]\[\"<>]*(?:doi\.org|/doi/|pnas\.org|science(?:mag)?\.org|"
    r"nature\.com|springer|wiley|sciencedirect|cell\.com|iopscience|agupubs|"
    r"rsc\.org|acs\.org|copernicus\.org|arxiv|plos|frontiersin|tandfonline|"
    r"cambridge\.org|oup\.com|ametsoc|biogeosciences|iop\.org|ciunit\.org)"
    # stop at Markdown/HTML delimiters too, or the match runs past "](" into
    # the next link
    r"[^\s\)\(\]\[\"<>]*", re.I)


def load_classification():
    rows = {}
    f = ROOT / "tools" / "post-classification.tsv"
    for line in f.read_text().splitlines():
        line = line.rstrip()
        if not line or line.startswith("#") or "\t" not in line:
            continue
        parts = line.split("\t")
        if len(parts) >= 2:
            rows[parts[0].strip()] = (parts[1].strip(),
                                      parts[2].strip() if len(parts) > 2 else "")
    return rows


def main():
    cls = load_classification()
    posts = []
    for f in sorted(POSTS.glob("*.md")):
        t = f.read_text()
        fm = t.split("---", 2)[1]
        body = t.split("---", 2)[2]
        slug = re.search(r"^slug: (.*)$", fm, re.M).group(1).strip()
        title = re.search(r'^title: "(.*)"$', fm, re.M).group(1)
        date = f.name[:10]
        cat, note = cls.get(slug, ("unclassified", ""))
        links = []
        for u in PUBLISHER.findall(body):
            u = u.rstrip(".,;)")
            # Signed, time-limited download URLs (publisher supplementary
            # files) are already expired and useless to a reader.
            if "Signature=" in u or "Expires=" in u:
                u = u.split("?")[0] + "  (signed URL, expired)"
            if u not in links:
                links.append(u)
        posts.append(dict(
            slug=slug, title=title, date=date, cat=cat, note=note,
            url=f"{SITE}/{date[:4]}/{date[5:7]}/{slug}/",
            file=f"_posts/{f.name}",
            words=len(re.findall(r"\w+", body)),
            images=len(re.findall(r"include (?:figure|gallery)\.html", body)),
            videos=len(re.findall(r"include youtube\.html", body)),
            links=links,
        ))

    by_cat = defaultdict(list)
    for p in posts:
        by_cat[p["cat"]].append(p)
    for v in by_cat.values():
        v.sort(key=lambda p: p["date"], reverse=True)

    L = []
    A = L.append
    A("# Candidate posts to move to CIunit")
    A("")
    A("Ken Caldeira's blog at <https://kencaldeira.com> holds 72 posts written "
      "between 2015 and 2025. Some are write-ups of peer-reviewed papers and "
      "would sit more naturally on CIunit; others are personal writing that "
      "should stay on the blog.")
    A("")
    A("**Purpose of this document:** hand it to whoever is building "
      "`ciunit.github.io` so they can see what content is available, what each "
      "post contains, and where to find the source. Once a post has been moved "
      "to CIunit, it can be deleted from the blog (and ideally redirected).")
    A("")
    A("Generated by `tools/ciunit_handoff.py` from `tools/post-classification.tsv`. "
      "The categories are a judgment call — edit that TSV and re-run to revise them.")
    A("")
    A("## Summary")
    A("")
    A("| Category | Posts | Words | Images |")
    A("|---|---:|---:|---:|")
    for key, label, _ in CATEGORIES:
        g = by_cat.get(key, [])
        A(f"| {label} | {len(g)} | {sum(p['words'] for p in g):,} | "
          f"{sum(p['images'] for p in g)} |")
    A(f"| **Total** | **{len(posts)}** | **{sum(p['words'] for p in posts):,}** | "
      f"**{sum(p['images'] for p in posts)}** |")
    A("")
    A("## How the source is laid out")
    A("")
    A("Each post is one Markdown file in `_posts/` of the "
      "`KCaldeira/kcaldeira.github.io` repository, named "
      "`YYYY-MM-DD-slug.md`, with YAML front matter (`title`, `date`, `slug`, "
      "`wp_id`). Body conventions, which a receiving site will need to handle "
      "or translate:")
    A("")
    A('- Images: `{% include figure.html src="/assets/images/YYYY/MM/file.png" '
      'alt="…" caption="…" %}` — the files live under `assets/images/` in the '
      "same repo, already web-optimized.")
    A('- YouTube: `{% include youtube.html id="…" %}`')
    A('- Galleries: `{% include gallery.html srcs="a|b|c" %}`')
    A("- Tables are GitHub-flavoured Markdown pipe tables.")
    A('- A few posts use `<span class="tc-blue">…</span>` and similar. **This '
      'is meaningful, not decorative** — it marks quoted email and external '
      "material. Preserve the distinction if these posts move.")
    A("")

    for key, label, blurb in CATEGORIES:
        g = by_cat.get(key, [])
        A("---")
        A("")
        A(f"## {label} ({len(g)})")
        A("")
        A(blurb)
        A("")
        if key == "personal":
            A("| Date | Post | Words |")
            A("|---|---|---:|")
            for p in g:
                A(f"| {p['date']} | [{p['title']}]({p['url']}) | {p['words']:,} |")
            A("")
            continue
        for p in g:
            A(f"### {p['title']}")
            A("")
            A(f"- **Live:** <{p['url']}>")
            A(f"- **Source:** `{p['file']}`")
            bits = [f"{p['words']:,} words"]
            if p["images"]:
                bits.append(f"{p['images']} image(s)")
            if p["videos"]:
                bits.append(f"{p['videos']} video embed(s)")
            A(f"- **Size:** {', '.join(bits)}")
            if p["note"]:
                A(f"- **Subject:** {p['note']}")
            if p["links"]:
                A("- **Cites:**")
                for u in p["links"][:12]:
                    A(f"  - <{u}>")
            A("")

    unclassified = by_cat.get("unclassified", [])
    if unclassified:
        A("---")
        A("")
        A(f"## Unclassified ({len(unclassified)})")
        A("")
        A("Not present in `tools/post-classification.tsv` — needs a category.")
        A("")
        for p in unclassified:
            A(f"- [{p['title']}]({p['url']}) — `{p['file']}`")
        A("")

    A("---")
    A("")
    A("## When a post moves")
    A("")
    A("1. Recreate it on CIunit, bringing its images across from "
      "`assets/images/`.")
    A("2. Delete the Markdown file from `_posts/` and run "
      "`.venv/bin/python tools/images.py prune` to drop assets no longer "
      "referenced.")
    A("3. **Leave a redirect.** Every post URL has been live since as early as "
      "2015 and is indexed; deleting one without a redirect breaks inbound "
      "links. GitHub Pages supports this via the `jekyll-redirect-from` plugin "
      "(on GitHub's allowlist), or by leaving a stub page that points at the "
      "CIunit location.")
    A("4. Re-run `.venv/bin/python tools/verify.py` — it checks every original "
      "WordPress URL still resolves, and will flag any that stopped.")
    A("")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT.name}")
    for key, label, _ in CATEGORIES:
        g = by_cat.get(key, [])
        print(f"  {len(g):3d}  {label}")
    if unclassified:
        print(f"  {len(unclassified):3d}  UNCLASSIFIED")


if __name__ == "__main__":
    main()
